language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-polunware' ]; then cd .. && eval "mv $currentfolder generator-polunware" && cd generator-polunware; fi

